In [1]:
import os
print(os.getcwd())

C:\Users\satya

In [1]:
import pandas as pd

In [4]:
df=pd.read_csv("Study Hour(Linear Regression).csv")

In [5]:
df

    Hours  Scores
0     2.5      21
1     5.1      47
2     3.2      27
3     8.5      75
4     3.5      30
5     1.5      20
6     9.2      88
7     5.5      60
8     8.3      81
9     2.7      25
10    7.7      85
11    5.9      62
12    4.5      41
13    3.3      42
14    1.1      17
15    8.9      95
16    2.5      30
17    1.9      24
18    6.1      67
19    7.4      69
20    2.7      30
21    4.8      54
22    3.8      35
23    6.9      76
24    7.8      86

In [3]:
import requests 
from io import StringIO
url=""
headers = {"User-Agent": "Mozilla/5.0"}
req=request.get(url,headers=headers)
data=StringIO(req.text)
pd.read_csv(data)

NameError: name 'request' is not defined

In [9]:
pd.read_csv("Study Hour(Linear Regression).csv",usecols=['Hours']).squeeze()

0     2.5
1     5.1
2     3.2
3     8.5
4     3.5
5     1.5
6     9.2
7     5.5
8     8.3
9     2.7
10    7.7
11    5.9
12    4.5
13    3.3
14    1.1
15    8.9
16    2.5
17    1.9
18    6.1
19    7.4
20    2.7
21    4.8
22    3.8
23    6.9
24    7.8
Name: Hours, dtype: float64

In [8]:
pd.read_csv("Study Hour(Linear Regression).csv",usecols=['Hours'])

    Hours
0     2.5
1     5.1
2     3.2
3     8.5
4     3.5
5     1.5
6     9.2
7     5.5
8     8.3
9     2.7
10    7.7
11    5.9
12    4.5
13    3.3
14    1.1
15    8.9
16    2.5
17    1.9
18    6.1
19    7.4
20    2.7
21    4.8
22    3.8
23    6.9
24    7.8

In [11]:
pd.read_csv("Study Hour(Linear Regression).csv",nrows=10)

   Hours  Scores
0    2.5      21
1    5.1      47
2    3.2      27
3    8.5      75
4    3.5      30
5    1.5      20
6    9.2      88
7    5.5      60
8    8.3      81
9    2.7      25

In [12]:
!pip install mysql.connector

WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 407 Proxy Authentication Required'))': /simple/mysql-connector/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 407 Proxy Authentication Required'))': /simple/mysql-connector/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 407 Proxy Authentication Required'))': /simple/mysql-connector/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 407 Proxy Authentication Required'))': /simple/mysql-connector/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 407 Proxy Authentication Required'))': /simple/mysql-connector/
ERROR: Could not find a version that satisfies the requirement mysql.connector (from versions: none)
ERROR: No matching distribution found for mysql.connector

In [13]:
import mysql.connector

ModuleNotFoundError: No module named 'mysql'

In [15]:
conn=mysql.connector.connect(host='localhost',user='root',password='',database='world')

NameError: name 'mysql' is not defined

In [ ]:
pd.read_sql_query('SELECT * FROM City',conn)